on:
  pull_request:
    branches:
    - main

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04 

    steps:
      - run: npm install
        if: github.event_name == 'pull_request'
